name: Executable

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: python -m pip install -r requirements.txt
      - run: python -m PyInstaller --onefile --noconsole shot-peening-viewer.py
      - uses: actions/upload-artifact@v2
        with:
          name: "shot-peening-viewer_${{ runner.os }}"
          path: dist

  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - uses: release-drafter/release-drafter@v5
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v2
        with:
          name: shot-peening-viewer_Linux
          path: dist/linux
      - run: chmod +x dist/linux/shot-peening-viewer
      - run: tar -pczvf linux.tar.gz -C dist/linux shot-peening-viewer
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./linux.tar.gz
          asset_name: shot-peening-viewer_standalone_linux-x64.tar.gz
          asset_content_type: application/octet-stream

      - uses: actions/download-artifact@v2
        with:
          name: shot-peening-viewer_macOS
          path: dist/macos
      - run: chmod +x dist/macos/shot-peening-viewer
      - run: tar -pczvf macos.tar.gz -C dist/macos shot-peening-viewer
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./macos.tar.gz
          asset_name: shot-peening-viewer_standalone_macos-x64.tar.gz
          asset_content_type: application/octet-stream

      - uses: actions/download-artifact@v2
        with:
          name: shot-peening-viewer_Windows
          path: dist/windows
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/windows/shot-peening-viewer.exe
          asset_name: shot-peening-viewer_standalone_windows-x64.exe
          asset_content_type: application/octet-stream
